# Generated by Django 4.0.4 on 2022-05-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('company_url', models.CharField(max_length=500)),
                ('market', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Acquired', 'Acquired'), ('Operating', 'Operating'), ('Closed', 'Closed')], default='Acquired', max_length=20)),
            ],
        ),
    ]
