# Generated by Django 4.0.4 on 2022-05-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=250)),
                ('market', models.CharField(max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('1', 'Acquired'), ('0', 'Closed')], default='1', max_length=2)),
                ('founding_year', models.IntegerField(default=2010)),
                ('founding_quarter', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('total_investment', models.BigIntegerField()),
                ('seed', models.BigIntegerField()),
                ('venture', models.BigIntegerField()),
                ('equity_crowdfunding', models.BigIntegerField()),
                ('undisclosed', models.BigIntegerField()),
                ('convertible_note', models.BigIntegerField()),
                ('debt_financing', models.BigIntegerField()),
                ('angel', models.BigIntegerField()),
                ('grant_given', models.BigIntegerField()),
                ('private_equity', models.BigIntegerField()),
                ('post_ipo_equity', models.BigIntegerField()),
                ('post_ipo_debt', models.BigIntegerField()),
                ('secondary_market', models.BigIntegerField()),
                ('product_crowdfunding', models.BigIntegerField()),
                ('round_A', models.BigIntegerField()),
                ('round_B', models.BigIntegerField()),
                ('round_C', models.BigIntegerField()),
                ('round_D', models.BigIntegerField()),
                ('round_E', models.BigIntegerField()),
                ('round_F', models.BigIntegerField()),
                ('round_G', models.BigIntegerField()),
                ('round_H', models.BigIntegerField()),
            ],
        ),
    ]
