# Generated by Django 4.0.4 on 2022-05-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='company_url',
        ),
        migrations.AddField(
            model_name='companies',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
