# Generated by Django 4.0.4 on 2022-05-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_companies_company_url_companies_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='id',
        ),
        migrations.AddField(
            model_name='companies',
            name='founding_quarter',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='companies',
            name='founding_year',
            field=models.IntegerField(default=2010),
        ),
        migrations.AlterField(
            model_name='companies',
            name='company_name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='companies',
            name='status',
            field=models.CharField(choices=[('1', 'Acquired'), ('0', 'Closed')], default='1', max_length=2),
        ),
    ]
