# Generated by Django 4.0.4 on 2022-05-19 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_companies_id_companies_founding_quarter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_investment', models.IntegerField()),
                ('seed', models.IntegerField()),
                ('venture', models.IntegerField()),
                ('equity_crowdfunding', models.IntegerField()),
                ('undisclosed', models.IntegerField()),
                ('convertible_note', models.IntegerField()),
                ('debt_financing', models.IntegerField()),
                ('angel', models.IntegerField()),
                ('grant', models.IntegerField()),
                ('private_equity', models.IntegerField()),
                ('post_ipo_equity', models.IntegerField()),
                ('post_ipo_debt', models.IntegerField()),
                ('secondary_market', models.IntegerField()),
                ('product_crowdfunding', models.IntegerField()),
                ('round_A', models.IntegerField()),
                ('round_B', models.IntegerField()),
                ('round_C', models.IntegerField()),
                ('round_D', models.IntegerField()),
                ('round_E', models.IntegerField()),
                ('round_F', models.IntegerField()),
                ('round_G', models.IntegerField()),
                ('round_H', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companies')),
            ],
        ),
    ]
