# Generated by Django 4.0.4 on 2022-05-19 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_finances'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finances',
            old_name='name',
            new_name='company_name',
        ),
    ]
