# Generated by Django 4.0.4 on 2022-05-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_rename_name_finances_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finances',
            old_name='grant',
            new_name='grant_given',
        ),
    ]
